[2023-08-04T10:49:35.424+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: toronto_real_estate_etl.Transform manual__2023-08-04T09:33:43.522776+00:00 [queued]>
[2023-08-04T10:49:35.430+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: toronto_real_estate_etl.Transform manual__2023-08-04T09:33:43.522776+00:00 [queued]>
[2023-08-04T10:49:35.430+0000] {taskinstance.py:1308} INFO - Starting attempt 2 of 2
[2023-08-04T10:49:35.439+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): Transform> on 2023-08-04 09:33:43.522776+00:00
[2023-08-04T10:49:35.443+0000] {standard_task_runner.py:57} INFO - Started process 1559 to run task
[2023-08-04T10:49:35.445+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'toronto_real_estate_etl', 'Transform', 'manual__2023-08-04T09:33:43.522776+00:00', '--job-id', '112', '--raw', '--subdir', 'DAGS_FOLDER/etl.py', '--cfg-path', '/tmp/tmpbbiwnnq0']
[2023-08-04T10:49:35.447+0000] {standard_task_runner.py:85} INFO - Job 112: Subtask Transform
[2023-08-04T10:49:35.479+0000] {task_command.py:410} INFO - Running <TaskInstance: toronto_real_estate_etl.Transform manual__2023-08-04T09:33:43.522776+00:00 [running]> on host e5187b3c4256
[2023-08-04T10:49:35.527+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='toronto_real_estate_etl' AIRFLOW_CTX_TASK_ID='Transform' AIRFLOW_CTX_EXECUTION_DATE='2023-08-04T09:33:43.522776+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-08-04T09:33:43.522776+00:00'
[2023-08-04T10:49:35.533+0000] {Transform.py:44} INFO - /opt/***/dags/transformed/2023-08-04/page_number_1.json
[2023-08-04T10:49:35.534+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/src/main.py", line 45, in transform
    t.saveToJson(date)
  File "/opt/airflow/dags/src/Transform.py", line 45, in saveToJson
    with open(filename, 'w+') as fp:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/dags/transformed/2023-08-04/page_number_1.json'
[2023-08-04T10:49:35.539+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=toronto_real_estate_etl, task_id=Transform, execution_date=20230804T093343, start_date=20230804T104935, end_date=20230804T104935
[2023-08-04T10:49:35.545+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 112 for task Transform ([Errno 2] No such file or directory: '/opt/airflow/dags/transformed/2023-08-04/page_number_1.json'; 1559)
[2023-08-04T10:49:35.577+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-08-04T10:49:35.593+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
