[2023-07-28T15:22:39.600+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: toronto_real_estate_etl.RawToS3 manual__2023-07-28T15:22:33.470632+00:00 [queued]>
[2023-07-28T15:22:39.606+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: toronto_real_estate_etl.RawToS3 manual__2023-07-28T15:22:33.470632+00:00 [queued]>
[2023-07-28T15:22:39.606+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-07-28T15:22:39.615+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): RawToS3> on 2023-07-28 15:22:33.470632+00:00
[2023-07-28T15:22:39.620+0000] {standard_task_runner.py:57} INFO - Started process 147 to run task
[2023-07-28T15:22:39.622+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'toronto_real_estate_etl', 'RawToS3', 'manual__2023-07-28T15:22:33.470632+00:00', '--job-id', '32', '--raw', '--subdir', 'DAGS_FOLDER/etl.py', '--cfg-path', '/tmp/tmpdjkgkm6h']
[2023-07-28T15:22:39.624+0000] {standard_task_runner.py:85} INFO - Job 32: Subtask RawToS3
[2023-07-28T15:22:39.657+0000] {task_command.py:410} INFO - Running <TaskInstance: toronto_real_estate_etl.RawToS3 manual__2023-07-28T15:22:33.470632+00:00 [running]> on host e5187b3c4256
[2023-07-28T15:22:39.710+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='toronto_real_estate_etl' AIRFLOW_CTX_TASK_ID='RawToS3' AIRFLOW_CTX_EXECUTION_DATE='2023-07-28T15:22:33.470632+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-07-28T15:22:33.470632+00:00'
[2023-07-28T15:22:39.915+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/src/main.py", line 91, in uploadRawtoS3
    upload_to_s3(originalFile)
  File "/opt/airflow/dags/src/Upload.py", line 28, in upload_to_s3
    upload_file_to_s3(conn,file)
  File "/opt/airflow/dags/src/Upload.py", line 47, in upload_file_to_s3
    result = conn.Bucket(BUCKET_NAME).upload_file('data/'+file,'data/{}'.format(file))
  File "/home/airflow/.local/lib/python3.7/site-packages/boto3/s3/inject.py", line 239, in bucket_upload_file
    Config=Config,
  File "/home/airflow/.local/lib/python3.7/site-packages/boto3/s3/inject.py", line 148, in upload_file
    callback=Callback,
  File "/home/airflow/.local/lib/python3.7/site-packages/boto3/s3/transfer.py", line 292, in upload_file
    future.result()
  File "/home/airflow/.local/lib/python3.7/site-packages/s3transfer/futures.py", line 103, in result
    return self._coordinator.result()
  File "/home/airflow/.local/lib/python3.7/site-packages/s3transfer/futures.py", line 266, in result
    raise self._exception
  File "/home/airflow/.local/lib/python3.7/site-packages/s3transfer/tasks.py", line 269, in _main
    self._submit(transfer_future=transfer_future, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/s3transfer/upload.py", line 585, in _submit
    upload_input_manager.provide_transfer_size(transfer_future)
  File "/home/airflow/.local/lib/python3.7/site-packages/s3transfer/upload.py", line 244, in provide_transfer_size
    self._osutil.get_file_size(transfer_future.meta.call_args.fileobj)
  File "/home/airflow/.local/lib/python3.7/site-packages/s3transfer/utils.py", line 247, in get_file_size
    return os.path.getsize(filename)
  File "/usr/local/lib/python3.7/genericpath.py", line 50, in getsize
    return os.stat(filename).st_size
FileNotFoundError: [Errno 2] No such file or directory: 'data//opt/airflow/dags/data/result_page_number_1_2023-07-28.json'
[2023-07-28T15:22:39.923+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=toronto_real_estate_etl, task_id=RawToS3, execution_date=20230728T152233, start_date=20230728T152239, end_date=20230728T152239
[2023-07-28T15:22:39.934+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 32 for task RawToS3 ([Errno 2] No such file or directory: 'data//opt/airflow/dags/data/result_page_number_1_2023-07-28.json'; 147)
[2023-07-28T15:22:39.954+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-07-28T15:22:39.980+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
