[2023-07-28T15:55:59.563+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: toronto_real_estate_etl.Transform manual__2023-07-28T15:40:11.619547+00:00 [queued]>
[2023-07-28T15:55:59.571+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: toronto_real_estate_etl.Transform manual__2023-07-28T15:40:11.619547+00:00 [queued]>
[2023-07-28T15:55:59.571+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-07-28T15:55:59.581+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): Transform> on 2023-07-28 15:40:11.619547+00:00
[2023-07-28T15:55:59.586+0000] {standard_task_runner.py:57} INFO - Started process 778 to run task
[2023-07-28T15:55:59.589+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'toronto_real_estate_etl', 'Transform', 'manual__2023-07-28T15:40:11.619547+00:00', '--job-id', '49', '--raw', '--subdir', 'DAGS_FOLDER/etl.py', '--cfg-path', '/tmp/tmplrn0wjma']
[2023-07-28T15:55:59.591+0000] {standard_task_runner.py:85} INFO - Job 49: Subtask Transform
[2023-07-28T15:55:59.629+0000] {task_command.py:410} INFO - Running <TaskInstance: toronto_real_estate_etl.Transform manual__2023-07-28T15:40:11.619547+00:00 [running]> on host e5187b3c4256
[2023-07-28T15:55:59.692+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='toronto_real_estate_etl' AIRFLOW_CTX_TASK_ID='Transform' AIRFLOW_CTX_EXECUTION_DATE='2023-07-28T15:40:11.619547+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-07-28T15:40:11.619547+00:00'
[2023-07-28T15:55:59.694+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/src/main.py", line 103, in transform
    t.transform()
  File "/opt/airflow/dags/src/Transform.py", line 14, in transform
    item['id'] = int(item['id'])
TypeError: string indices must be integers
[2023-07-28T15:55:59.701+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=toronto_real_estate_etl, task_id=Transform, execution_date=20230728T154011, start_date=20230728T155559, end_date=20230728T155559
[2023-07-28T15:55:59.709+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 49 for task Transform (string indices must be integers; 778)
[2023-07-28T15:55:59.721+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-07-28T15:55:59.737+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
