[2023-08-01T11:22:30.407+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: toronto_real_estate_etl.ToStageTable manual__2023-08-01T11:16:42.810577+00:00 [queued]>
[2023-08-01T11:22:30.415+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: toronto_real_estate_etl.ToStageTable manual__2023-08-01T11:16:42.810577+00:00 [queued]>
[2023-08-01T11:22:30.415+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-08-01T11:22:30.427+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): ToStageTable> on 2023-08-01 11:16:42.810577+00:00
[2023-08-01T11:22:30.431+0000] {standard_task_runner.py:57} INFO - Started process 636 to run task
[2023-08-01T11:22:30.434+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'toronto_real_estate_etl', 'ToStageTable', 'manual__2023-08-01T11:16:42.810577+00:00', '--job-id', '77', '--raw', '--subdir', 'DAGS_FOLDER/etl.py', '--cfg-path', '/tmp/tmpf_e467lj']
[2023-08-01T11:22:30.436+0000] {standard_task_runner.py:85} INFO - Job 77: Subtask ToStageTable
[2023-08-01T11:22:30.474+0000] {task_command.py:410} INFO - Running <TaskInstance: toronto_real_estate_etl.ToStageTable manual__2023-08-01T11:16:42.810577+00:00 [running]> on host e5187b3c4256
[2023-08-01T11:22:30.529+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='toronto_real_estate_etl' AIRFLOW_CTX_TASK_ID='ToStageTable' AIRFLOW_CTX_EXECUTION_DATE='2023-08-01T11:16:42.810577+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-08-01T11:16:42.810577+00:00'
[2023-08-01T11:22:32.775+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/src/main.py", line 100, in insertIntoStage
    load(filepath)
  File "/opt/airflow/dags/src/Load.py", line 150, in load
    L.loadValues(filename=filename)
  File "/opt/airflow/dags/src/Load.py", line 128, in loadValues
    execute_values(cursor, query, values)
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/extras.py", line 1299, in execute_values
    cur.execute(b''.join(parts))
psycopg2.errors.UndefinedTable: relation "stage_table" does not exist

[2023-08-01T11:22:32.783+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=toronto_real_estate_etl, task_id=ToStageTable, execution_date=20230801T111642, start_date=20230801T112230, end_date=20230801T112232
[2023-08-01T11:22:32.791+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 77 for task ToStageTable (relation "stage_table" does not exist
; 636)
[2023-08-01T11:22:32.818+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-08-01T11:22:32.834+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
